### ISSUE TITLE
Can't open Downloads folder if it contains files or folders with Japanese names

### ISSUE THREAD

**Issue by dpalacio** [flathub/org.openstreetmap.josm#31]
==== What steps will reproduce the problem?
1. Click on the open button
2. That's it.

It will show a "You have encountered a bug in JOSM" window.

==== What is the expected result?
It will list the contents of my Downloads folder

==== What happens instead?
It chokes with the folder contents that have filenames with Japanese characters.

==== Please provide any additional information below. Attach a screenshot if possible.
Running Debian Unstable/Plasma Desktop with JOSM from the flathub repository.
My system locale is es_CO.utf8

I tested the Debian provided JOSM package and it doesn't have this problem. Only the flathub one does.

{{{
Relative:URL: ^/trunk
Repository:UUID: 0c6e7542-c601-0410-84e7-c038aed88b3b
Last:Changed Date: 2020-12-28 22:03:23 +0100 (Mon, 28 Dec 2020)
Revision:17428
Build-Date:2020-12-30 02:30:55
URL:https://josm.openstreetmap.de/svn/trunk

Identification: JOSM/1.5 (17428 en) Linux Freedesktop.org 20.08.3 (Flatpak runtime)
Memory Usage: 264 MB / 3502 MB (89 MB allocated, but free)
Java version: 11.0.8+10, Flathub, OpenJDK 64-Bit Server VM
Look and Feel: javax.swing.plaf.metal.MetalLookAndFeel
Screen: :0.0 1920×1080 (scaling 1.00×1.00)
Maximum Screen Size: 1920×1080
Best cursor sizes: 16×16→16×16, 32×32→32×32
Desktop environment: KDE
Environment variable LANG: en_US.UTF-8

Last errors/warnings:
- 00245.139 E: Handled by bug report queue: java.nio.file.InvalidPathException: Malformed input or input contains unmappable characters: ${HOME}/Descargas/[binary gibberish]

=== REPORTED CRASH DATA ===
BugReportExceptionHandler#handleException:
No data collected.

Warning issued by: BugReportExceptionHandler#handleException

=== STACK TRACE ===
Thread: Basic L&F File Loading Thread (62)
java.nio.file.InvalidPathException: Malformed input or input contains unmappable characters: /home/user/Descargas/[binary gibberish]
	at java.base/sun.nio.fs.UnixPath.encode(UnixPath.java:145)
	at java.base/sun.nio.fs.UnixPath.<init>(UnixPath.java:69)
	at java.base/sun.nio.fs.UnixFileSystem.getPath(UnixFileSystem.java:279)
	at java.base/java.nio.file.Path.of(Path.java:147)
	at java.base/java.nio.file.Paths.get(Paths.java:69)
	at java.desktop/sun.awt.shell.ShellFolder.getShellFolder(ShellFolder.java:247)
	at java.desktop/javax.swing.filechooser.FileSystemView.getFiles(FileSystemView.java:523)
	at java.desktop/javax.swing.plaf.basic.BasicDirectoryModel$FilesLoader.run0(BasicDirectoryModel.java:290)
	at java.desktop/javax.swing.plaf.basic.BasicDirectoryModel$FilesLoader.run(BasicDirectoryModel.java:279)
	at java.base/java.lang.Thread.run(Thread.java:834)
}}}

=== EXTRA ===
Is there a reason you cannot allow access to the whole home folder? The Blender flatpak has free access to it, for example.

**Comment by simon04** [comment]
@JOSM ticket: https://josm.openstreetmap.de/ticket/14596

Related to non-UTF-8 `file.encoding`, for instance:

```
Environment variable LANG: en_GB.UTF-8
System property file.encoding: ANSI_X3.4-1968
System property sun.jnu.encoding: ANSI_X3.4-1968
```

**Comment by tsmock** [comment]
I just made a PR at flathub/org.freedesktop.Sdk.Extension.openjdk/pull/12 updating the org.freedesktop.Sdk.Extension.openjdk extension to Java 18. I _believe but have not verified_ that JEP 400 (UTF-8 by default) will fix this issue.

Assuming the PR is merged, this issue _may_ be fixed by doing the following:
```diff
diff --git a/org.openstreetmap.josm.yaml b/org.openstreetmap.josm.yaml
index ba36cfb..2fc4d85 100644
--- a/org.openstreetmap.josm.yaml
+++ b/org.openstreetmap.josm.yaml
@@ -3,7 +3,7 @@ runtime: org.freedesktop.Platform
 runtime-version: '21.08'
 sdk: org.freedesktop.Sdk
 sdk-extensions:
-  - org.freedesktop.Sdk.Extension.openjdk17
+  - org.freedesktop.Sdk.Extension.openjdk
 command: josm
 rename-icon: josm
 finish-args:
@@ -16,7 +16,7 @@ finish-args:
 
 build-options:
   env:
-    JAVA_HOME: /usr/lib/sdk/openjdk17/
+    JAVA_HOME: /usr/lib/sdk/openjdk/
 modules:
   - name: xgetres
     buildsystem: simple
@@ -31,7 +31,7 @@ modules:
   - name: openjdk
     buildsystem: simple
     build-commands:
-      - /usr/lib/sdk/openjdk17/install.sh
+      - /usr/lib/sdk/openjdk/install.sh
 
 
   - name: josm-binary
```

**Comment by muelli** [comment]
uh. is the JDK then not versioned? That's even worse than it currently is, where don't know which particular version of the extension has been loaded at a given time.

Anyway, the modification LGTM and I'm happy if you make a PR.

**Comment by tsmock** [comment]
I'll go ahead and make a PR once the openjdk repo merges the PR to update to Java 18.

The org.freedesktop.Sdk.Extension.openjdk is "unversioned" in that it _should be_ the latest version of Java.

JOSM doesn't really care what version of Java it is running on, so long as it is Java 8 or later (although we are strongly encouraging Java 11 or later).

JOSM has CI jobs for the following Java versions:
* Java 8 (I am _really hoping_ to move off of Java 8 this year)
* Java 11
* Java 17
* Java 18
* Java 19 (ea, I'm working on fixing the build process for this)

Rather unfortunately, the next expected LTS is Java 21 (September 2023), so the flatpak will probably have to ride the latest Java train for awhile, instead of using an LTS.

So, for JOSM, the only important thing is that the Java version is equal to or newer than Java 11, and for flatpak, Java 18 might fix the unmappable character problem.

**Comment by muelli** [comment]
> The org.freedesktop.Sdk.Extension.openjdk is "unversioned" in that it _should be_ the latest version of Java.

I think that's a terrible idea, but that's not relevant for this discussion here.

Thanks for your investigation and the patch! :)
