### ISSUE TITLE
No X11 DISPLAY variable was set

### ISSUE THREAD

**Issue by u6aab** [flathub/org.openstreetmap.josm#88]
I'm using fedora 38 with kde. when I try to launch josm from the desktop launcher, the icon on the panel disappears after a few seconds, no gui is shown but system monitor reports it running. when trying to launch from the command line I get this error:

`
[user@fedora ~]$ flatpak run org.openstreetmap.josm
Using /app/jre/bin/java to execute josm.
Can't open display
2023-10-16 17:02:39.420 INFO: Log level is at INFO (INFO, 800)
2023-10-16 17:02:40.863 SEVERE: Handled by bug report queue: java.awt.HeadlessException: No X11 DISPLAY variable was set,
but this program performed an operation which requires it.
java.awt.HeadlessException: 
No X11 DISPLAY variable was set,
but this program performed an operation which requires it.
        at java.desktop/java.awt.GraphicsEnvironment.checkHeadless(GraphicsEnvironment.java:166)
        at java.desktop/java.awt.Window.<init>(Window.java:553)
        at java.desktop/java.awt.Frame.<init>(Frame.java:428)
        at java.desktop/java.awt.Frame.<init>(Frame.java:393)
        at java.desktop/javax.swing.JFrame.<init>(JFrame.java:180)
        at org.openstreetmap.josm.gui.MainFrame.<init>(MainFrame.java:74)
        at org.openstreetmap.josm.gui.MainApplication.createMainFrame(MainApplication.java:1004)
        at org.openstreetmap.josm.gui.MainApplication.mainJOSM(MainApplication.java:853)
        at org.openstreetmap.josm.gui.MainApplication$3.processArguments(MainApplication.java:277)
        at org.openstreetmap.josm.gui.MainApplication.main(MainApplication.java:742)
ReportedException [thread=Thread[main,5,], exception=java.awt.HeadlessException: 
No X11 DISPLAY variable was set,
but this program performed an operation which requires it., methodWarningFrom=BugReportExceptionHandler#handleException]
        at org.openstreetmap.josm.tools.bugreport.BugReport.intercept(BugReport.java:213)
        at org.openstreetmap.josm.tools.bugreport.BugReportExceptionHandler.handleException(BugReportExceptionHandler.java:22)
        at org.openstreetmap.josm.tools.bugreport.BugReportExceptionHandler.uncaughtException(BugReportExceptionHandler.java:14)
        at java.base/java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1082)
        at java.base/java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1077)
        at java.base/java.lang.Thread.dispatchUncaughtException(Thread.java:2008)
Caused by: java.awt.HeadlessException: 
No X11 DISPLAY variable was set,
but this program performed an operation which requires it.
        at java.desktop/java.awt.GraphicsEnvironment.checkHeadless(GraphicsEnvironment.java:166)
        at java.desktop/java.awt.Window.<init>(Window.java:553)
        at java.desktop/java.awt.Frame.<init>(Frame.java:428)
        at java.desktop/java.awt.Frame.<init>(Frame.java:393)
        at java.desktop/javax.swing.JFrame.<init>(JFrame.java:180)
        at org.openstreetmap.josm.gui.MainFrame.<init>(MainFrame.java:74)
        at org.openstreetmap.josm.gui.MainApplication.createMainFrame(MainApplication.java:1004)
        at org.openstreetmap.josm.gui.MainApplication.mainJOSM(MainApplication.java:853)
        at org.openstreetmap.josm.gui.MainApplication$3.processArguments(MainApplication.java:277)
        at org.openstreetmap.josm.gui.MainApplication.main(MainApplication.java:742)
`

**Comment by muelli** [comment]
> java.awt.HeadlessException: No X11 DISPLAY variable was set,

hm. We're setting the app as X11 only: https://github.com/flathub/org.openstreetmap.josm/blob/a1eae34051a7b7f65dcc99e5c576768585bd344f/org.openstreetmap.josm.yaml#L10

I don't know what else we can do.
This should affect any other x11-only app, too.
